#!/bin/bash

function print_help() {
        echo "USAGE:
        gitSwitch <NAME>         Switch the current git profile with <NAME>
        gitSwitch help           Print this help message"
}

if [ "$XDG_CONFIG_HOME" == "" ]; then
        CONFIG_DIR=~/.config
else
        CONFIG_DIR=$XDG_CONFIG_HOME
fi

if [ -f $CONFIG_DIR/gitSwitch/$1 ]; then
        cp $CONFIG_DIR/gitSwitch/$1 ~/.gitconfig
elif [ "$1" == "help" ]; then
        print_help;
else
        echo "Invalid name:" $1;
        print_help;
fi
