#!/bin/bash

function print_help() {
        echo "USAGE:
        gitSwitch <NAME>         Switch the current git profile with <NAME>
        gitSwitch help           Print this help message"
}

if [ -f ~/.config/gitSwitch/$1 ]; then
        cp ~/.config/gitSwitch/$1 ~/.gitconfig
elif [ "$1" == "help" ]; then
        print_help;
else
        echo "Invalid name:" $1;
        print_help;
fi
